apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys
  namespace: jenkins
type: Opaque
data:
  authorized_keys: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDNFZrODJjMkZVMDdDazA3cHMzcCtZTFRTQXUranN6ZDlDTytSUW9FeDRnZW9EdDFsTFc2WjAzV0VEYUZQNTJlaDJBT3V5cWc5Mnp0NkhFdWhuUzJyMyt0eHhsVHk0VzNKV2Q1MVFMbHJ5NUJEK3pDL3JmY2FJWXpBanZsSTRDdnNKUCtxV0NZc2N2Q3NldVFzTjJvam5odmRiY1lyV1MvczZydFBiYzluNWc3QXF6MzB1ZmlRdW9LM1M5S1Fnb1EwYTVCaVpqTmdxUllyOGNKTDNhUXJzajBtcGJjNTRFQWtWTWlYcEUyUDJXZkhTaTNVVlh0enBBS0w4d3IzN3VXVlhxNjRKc2crTmU5bnFiVUVjT2xoL3d0alBUc1AwUUJVbEZiQnZXOXEybllyNnoxRlJvU2g0VW9HRlFkM3pHT05CRVJrL2MrU2I5b1hwRnpxaVE2R2wgcnVlZGlAZWxhcmEK
