apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  namespace: ssh
spec:
  type: LoadBalancer
  # loadBalancerIP: <YOUR LOAD BALANCER IP>
  selector:
    app: ssh
  ports:
    # the port that this service should serve on
  - port: 22
    protocol: TCP
    targetPort: 22
