apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh
  namespace: default
spec:
  selector:
    matchLabels:
      app: ssh
  replicas: 1
  template:
    metadata:
      labels:
        app: ssh
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: master
        image: rmariappan/sshd:0.3-testuserrun
        imagePullPolicy: Always
        command:
          - /usr/sbin/sshd
          - -D
          - -p
          - "2222"
          - -E
          - /tmp/ssh.log
        ports:
        - containerPort: 2222
        env:
        volumeMounts:
        - name: ssh-dir
          mountPath: /home/span/.ssh/authorized_keys
          subPath: authorized_keys
        - name: ssh-host-keys
          mountPath: /home/span/.ssh/hostKeys
        resources:
          limits:
            cpu: 50m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 20Mi
      volumes:
      - name: ssh-dir
        secret:
          secretName: ssh-keys
          defaultMode: 0600
      - name: ssh-host-keys
        secret:
          secretName: ssh-host-keys
          defaultMode: 0600
